### ISSUE TITLE
Setup for vscode

### ISSUE THREAD

**Issue by dioklecijan** [mozilla-neutrino/neutrino-dev#121]
It seems that vscode supports .eslintrc.json only. 
I can't make it work with .eslintrc.js

Any hint?

My .eslintrc.js:

```
const Neutrino = require('neutrino');
const pkg = require('./package.json');
const api = new Neutrino(pkg.config.presets);

module.exports = api.custom.eslintrc();
```

**Comment by jefffriesen** [comment]
This actually broke for me recently and I don't use vscode (I use Atom). Not sure what's going on but the error message I got in the Atom console was:
> [Linter] Error running ESLint Error: Cannot read config file: /.../approot/.eslintrc.js

I 'fixed' it by using a static `.eslintrc` file, which isn't really sustainable. I was waiting for version 5 to come out.

**Comment by eliperelman** [comment]
Unfortunately we can't natively support using eslintrc files that are JSON out of the box. Since the eslint configuration is code that can be distributed among many presets, the only realistic thing you could do would be to take the eslint configuration and duplicate it into the JSON configuration. Obviously this is not sustainable, but it would be an interim solution until your specific editor supported the JS configuration.

**Comment by Dbuggerx** [comment]
@dioklecijan: Add `"eslint.options": { "configFile": ".eslintrc.js" }` to your _settings.json_ file.
It works fine here using this config.

**Comment by eliperelman** [comment]
Sounds like we have a solution. Please re-open if something isn't working as expected.

**Comment by dioklecijan** [comment]
It works. Thank you @Dbuggerx .
Whenever I change my preset js file I need to reload vscode window. 
But it is a minor problem we could safely ignore.

**Comment by iongion** [comment]
@dioklecijan how does your `.eslintrc.js` look like ?
