### ISSUE TITLE
Unhashed assets are copied to build directory

### ISSUE THREAD

**Issue by SeeThruHead** [mozilla-neutrino/neutrino-dev#194]
assets included by `import Image from '../blah.gif' are included in the build folder. Both as hashed files as well as the original file and directory structure.

Is this a bug?

**Comment by eliperelman** [comment]
Right now this is expected behavior. The copy plugin copies all non-JS assets to the build directory in case they needed to be referenced by path/URL, as there is no guarantee that a project will consume these resources via imports.

We plan on changing this in Neutrino v6 to only copy static assets that live in some assets directory within the project.

**Comment by SeeThruHead** [comment]
Yeah I've just been digging into the code and i see the copy plugin there.

I'd like to disable it but can't figure out how to remove plugins via webpack chain.

**Comment by SeeThruHead** [comment]
for posterity

> You can delete plugins by deleting from their backing store, at .plugins:
> 
> neutrino.config.plugins.delete('copy');
