### ISSUE TITLE
how to test (community)presets 

### ISSUE THREAD

**Issue by lielran** [mozilla-neutrino/neutrino-dev#285]
I face some old(V5) presets [jke-neutrino-preset-react-mobx](https://github.com/joakimkemeny/jke-neutrino-preset-react-mobx) and try to upgrade it to V6. 
the first thing I search for was some kind of tests I could run to see if I broke anything. 

I didn't find any documentation about it...

1)how should we test presets? 
2)which framework/runner to use? (ava? just? other?)
3)how can I test it locally before publish it to npm?

**Comment by nikolay** [comment]
I feel like Neutrino creates more work than it saves. Webpack v3 is out and who knows when Neutrino v7 will be out with support for it! I honestly don't see much value compared to [webpack-merge](https://www.npmjs.com/package/webpack-merge) or [webpack-config](https://www.npmjs.com/package/webpack-config) at this pace of development and added complexity! For a simple example, Neutrino works just fine, but for a real-world app, it's more work than just using React with Webpack, for example - especially via [create-react-app](https://www.npmjs.com/package/create-react-app)!

**Comment by eliperelman** [comment]
@nikolay feel free to use create-react-app if it serves your needs. The point of Neutrino is to give a common API and configuration that will work across many different types of projects, not just React.

With that said, remember that this is a community and open source project, and it takes contributors putting in their time to ship Neutrino v7. We hope to have it out this week maybe, but I am traveling so that isn't a guarantee.

In the future, let's keep conversation on-topic.

**Comment by eliperelman** [comment]
@lielran There isn't any particular guide to testing out presets for proper functionality, this would be whatever you desire. If you like, you can take a look at what we are currently doing in Neutrino by looking at any of the presets or middleware package directories, and see the test files.

**Comment by barraponto** [comment]
I think we could do a better job of testing and documenting how to test the presets.
I'm maintaining quite a few middlewares and presets, yet I'm not running tests for any of them :/
Right now, every time I make an upgrade I have to write stub projects to test it out ...
