### ISSUE TITLE
Investigate moving to Babel 7 when it releases

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#316]
https://github.com/babel/babel/milestone/14

**Comment by graingert** [comment]
FYI CRA has already got a pre-release with a `Switch to Babel 7` #3522

**Comment by edmorley** [comment]
I have this mostly working locally.

However we need to first:
* update to Jest 22 (since it adds babel 7 support, by making babel-core a peerDep instead, so we can use the babel-core@^7 shim) - there were strange test failures on #770 which I've managed to resolve - PR #823 now opened 
* fix the Preact linting config (#821) since updating to babel 7 means likely dropping use of `babel-plugin-jsx-pragmatic` (since it tries to pull in a babel 6 plugin; and isn't very maintained) - and without linting working properly, people won't be warned about the need to add the explicit preact imports
