### ISSUE TITLE
Add the tests directory to default lint include

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#331]
Currently neutrino-middleware-eslint defaults the directory `include` list to just `[neutrino.options.source]`:
https://github.com/mozilla-neutrino/neutrino-dev/blob/10819ad89d9d408f79e29487af5ea430701ac6df/packages/neutrino-middleware-eslint/index.js#L30

It seems like linting should also be run against tests - and so `include` default instead to `[neutrino.options.source, neutrino.options.test]`. (At least for `neutrino lint` or `neutrino test`, perhaps not for start/build?)

Also it looks like the include/exclude from neutrino-preset-airbnb-base can be removed, since it's just repeating what is in neutrino-middleware-eslint:
https://github.com/mozilla-neutrino/neutrino-dev/blob/10819ad89d9d408f79e29487af5ea430701ac6df/packages/neutrino-preset-airbnb-base/index.js#L24

Thoughts? :-)

**Comment by eliperelman** [comment]
The reason why the test directory is currently left out is it usually requires a different set of linting rules because of the test environment, sometimes from assumed globals. My thoughts to this point have been, if they want tests linted, they can override to add the directory and make the changes to support their test environment.

If we had a good answer to this, I think I might be persuaded to switch it.

**Comment by edmorley** [comment]
Ah fair point - happy to punt on this :-)

**Comment by constgen** [comment]
Test middlewares can override this setting if they provide all necessary plugins for linting, are they?

**Comment by eliperelman** [comment]
Is the only thing stopping us there is augmenting the eslint changes based on test middleware lint overrides?

**Comment by edmorley** [comment]
I think we should do this - and just adjust the test presets to ensure they do the right thing. If there are any cases not covered by them, then it's up to the end user to either override `includes` or supplement globals/plugins.
