### ISSUE TITLE
Add neutrino.options.optimize

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#458]

**Comment by eliperelman** [comment]
I reverted #460 until we can get more discussion.

How should `neutrino.options.optimize` work when using raw optimizing middleware from outside a preset?

```js
module.exports = {
  use: [
    '@neutrinojs/minify'
  ]
};
```

Right now the option wouldn't do anything since this middleware isn't guarded by the option. Should we wrap the middleware in this option? Should we instead make this a middleware option for those presets?

```js
module.exports = {
  use: [
    ['@neutrinojs/web', {
      optimize: false
    }]
  ]
};
```

**Comment by timkelty** [comment]
Yeah…now that you bring that up - that confusion is probably the best argument against making this an api option.

I'm leaning towards just making it a middleware option for node and web.

Either that - or we could expose more of the middleware options, and allow them to be omitted when `false`.

```
module.exports = {
  use: [
    ['@neutrinojs/web', {
      imagemin: false,
      minify: false,
      chunk: false
    }]
  ]
};
```

**Comment by eliperelman** [comment]
Yeah lol, I didn't think of it until right after I merged it. I'm fine with keeping the option simple at the preset level, and allowing low-level changes via the API.

**Comment by eliperelman** [comment]
Closing this in favor of middleware-specific options.

**Comment by timkelty** [comment]
👍  We should keep this in mind next time we have the urge to add an api-level option.

IIRC, we moved `static` from being api-level to MW for similar reasons at the v6 release.
