### ISSUE TITLE
Sync up differences between the react and preact packages

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#473]
Diffing `packages/react/` and `packages/preact/` shows a few differences between the two, some of which are necessary but it would be good to sync the rest up.

**Comment by eliperelman** [comment]
Current diff:

```diff
diff --git a/packages/react/.npmignore b/packages/react/.npmignore
deleted file mode 100644
index 1933786..0000000
--- a/packages/react/.npmignore
+++ /dev/null
@@ -1 +0,0 @@
-/test/
diff --git a/packages/react/README.md b/packages/preact/README.md
index f55abc4..e05b9a1 100644
--- a/packages/react/README.md
+++ b/packages/preact/README.md
@@ -1,6 +1,6 @@
-# Neutrino React Preset
+# Neutrino Preact Preset
 
-`@neutrinojs/react` is a Neutrino preset that supports building React web applications.
+`@neutrinojs/preact` is a Neutrino preset that supports building Preact web applications.
 
 [![NPM version][npm-image]][npm-url]
 [![NPM downloads][npm-downloads]][npm-url]
@@ -8,11 +8,11 @@
 
 ## Features
 
-- Zero upfront configuration necessary to start developing and building a React web app
+- Zero upfront configuration necessary to start developing and building a Preact web app
 - Modern Babel compilation adding JSX and object rest spread syntax.
-- Support for React Hot Loader
 - Write JSX in .js or .jsx files
-- Automatic import of `React.createElement`, no need to import `react` or `React.createElement` yourself
+- Automatic import of `Preact.h`, no need to import `h` or `createElement` yourself
+- Compatibility and pre-configured aliasing for React-based modules and packages
 - Extends from [@neutrinojs/web](https://neutrino.js.org/packages/web)
   - Modern Babel compilation supporting ES modules, last 2 major browser versions, async functions, and dynamic imports
   - Webpack loaders for importing HTML, CSS, images, icons, fonts, and web workers
@@ -20,7 +20,7 @@
   - Automatic creation of HTML pages, no templating necessary
   - Hot Module Replacement support
   - Tree-shaking to create smaller bundles
-  - Production-optimized bundles with Babili minification, easy chunking, and scope-hoisted modules for faster execution
+  - Production-optimized bundles with Babel minification, easy chunking, and scope-hoisted modules for faster execution
   - Easily extensible to customize your project as needed
 
 ## Requirements
@@ -31,46 +31,60 @@
 
 ## Installation
 
-`@neutrinojs/react` can be installed via the Yarn or npm clients. Inside your project, make sure
-`neutrino` and `@neutrinojs/react` are development dependencies. You will also need React and React DOM for actual
-React development.
+`@neutrinojs/preact` can be installed via the Yarn or npm clients. Inside your project, make sure
+`neutrino` and `@neutrinojs/preact` are development dependencies. You will also need `preact` for actual
+Preact development.
 
 #### Yarn
 
 ```bash
-❯ yarn add --dev neutrino @neutrinojs/react
-❯ yarn add react react-dom
+❯ yarn add --dev neutrino @neutrinojs/preact
+❯ yarn add preact
 ```
 
 #### npm
 
 ```bash
-❯ npm install --save-dev neutrino @neutrinojs/react
-❯ npm install --save react react-dom
+❯ npm install --save-dev neutrino @neutrinojs/preact
+❯ npm install --save preact
+```
+
+If you want to import React-based modules or packages, you should also install the `preact-compat`
+compatibility layer:
+
+#### Yarn
+
+```bash
+❯ yarn add preact-compat
+```
+
+#### npm
+
+```bash
+❯ npm install --save preact-compat
 ```
 
 ## Project Layout
 
-`@neutrinojs/react` follows the standard [project layout](https://neutrino.js.org/project-layout) specified by Neutrino. This
+`@neutrinojs/preact` follows the standard [project layout](https://neutrino.js.org/project-layout) specified by Neutrino. This
 means that by default all project source code should live in a directory named `src` in the root of the
 project. This includes JavaScript files, CSS stylesheets, images, and any other assets that would be available
 to import your compiled project.
 
 ## Quickstart
 
-After installing Neutrino and the React preset, add a new directory named `src` in the root of the project, with
+After installing Neutrino and the Preact preset, add a new directory named `src` in the root of the project, with
 a single JS file named `index.js` in it.
 
 ```bash
 ❯ mkdir src && touch src/index.js
 ```
 
-This React preset exposes an element in the page with an ID of `root` to which you can mount your application. Edit
+This Preact preset exposes an element in the page with an ID of `root` to which you can mount your application. Edit
 your `src/index.js` file with the following:
 
 ```jsx
-import React from 'react';
-import { render } from 'react-dom';
+import { render } from 'preact';
 
 render(<h1>Hello world!</h1>, document.getElementById('root'));
 ```
@@ -80,8 +94,8 @@ Now edit your project's package.json to add commands for starting and building t
 ```json
 {
   "scripts": {
-    "start": "neutrino start --use @neutrinojs/react",
-    "build": "neutrino build --use @neutrinojs/react"
+    "start": "neutrino start --use @neutrinojs/preact",
+    "build": "neutrino build --use @neutrinojs/preact"
   }
 }
 ```
@@ -90,7 +104,7 @@ If you are using `.neutrinorc.js`, add this preset to your use array instead of
 
 ```js
 module.exports = {
-  use: ['@neutrinojs/react']
+  use: ['@neutrinojs/preact']
 };
 ```
 
@@ -114,7 +128,7 @@ Start the app, then open a browser to the address in the console:
 
 ## Building
 
-`@neutrinojs/react` builds static assets to the `build` directory by default when running `neutrino build`. Using
+`@neutrinojs/preact` builds static assets to the `build` directory by default when running `neutrino build`. Using
 the quick start example above as a reference:
 
 ```bash
@@ -128,7 +142,7 @@ Time: 9773ms
    index.dfbad882ab3d86bfd747.js     181 kB     index  [emitted]  index
  runtime.3d9f9d2453f192a2b10f.js    1.51 kB   runtime  [emitted]  runtime
                       index.html  846 bytes            [emitted]
-✨  Done in 14.62s.
+✨  Done in 4.62s.
 ```
 
 You can either serve or deploy the contents of this `build` directory as a static site.
@@ -138,11 +152,11 @@ You can either serve or deploy the contents of this `build` directory as a stati
 If you wish to copy files to the build directory that are not imported from application code, you can place
 them in a directory within `src` called `static`. All files in this directory will be copied from `src/static`
 to `build/static`. To change this behavior, specify your own patterns with
-[@neutrinojs/copy](../../packages/copy/README.md).
+[@neutrinojs/copy](https://neutrino.js.org/packages/copy).
 
 ## Paths
 
-The `@neutrinojs/web` preset loads assets relative to the path of your application by setting Webpack's
+The `@neutrinojs/preact` preset loads assets relative to the path of your application by setting Webpack's
 [`output.publicPath`](https://webpack.js.org/configuration/output/#output-publicpath) to `./`. If you wish to load
 assets instead from a CDN, or if you wish to change to an absolute path for your application, customize your build to
 override `output.publicPath`. See the [Customizing](#Customizing) section below.
@@ -150,16 +164,16 @@ override `output.publicPath`. See the [Customizing](#Customizing) section below.
 ## Preset options
 
 You can provide custom options and have them merged with this preset's default options to easily affect how this
-preset builds. You can modify React preset settings from `.neutrinorc.js` by overriding with an options object. Use
+preset builds. You can modify Preact preset settings from `.neutrinorc.js` by overriding with an options object. Use
 an array pair instead of a string to supply these options in `.neutrinorc.js`.
 
-The following shows how you can pass an options object to the React preset and override its options. See the
+The following shows how you can pass an options object to the Preact preset and override its options. See the
 [Web documentation](https://neutrino.js.org/packages/web#preset-options) for specific options you can override with this object.
 
 ```js
 module.exports = {
   use: [
-    ['@neutrinojs/react', {
+    ['@neutrinojs/preact', {
       /* preset options */
 
       // Example: disable Hot Module Replacement
@@ -167,7 +181,7 @@ module.exports = {
 
       // Example: change the page title
       html: {
-        title: 'Epic React App'
+        title: 'Epic Preact App'
       },
       
       // Target specific browsers with babel-preset-env
@@ -197,7 +211,7 @@ module.exports = {
 ## Customizing
 
 To override the build configuration, start with the documentation on [customization](https://neutrino.js.org/customization).
-`@neutrinojs/react` does not use any additional named rules, loaders, or plugins that aren't already in use by the
+`@neutrinojs/preact` does not use any additional named rules, loaders, or plugins that aren't already in use by the
 Web preset. See the [Web documentation customization](https://neutrino.js.org/packages/web#customizing)
 for preset-specific configuration to override.
 
@@ -212,66 +226,59 @@ array. You can also make these changes from the Neutrino API in custom middlewar
 By defining an entry point named `vendor` you can split out external dependencies into a chunk separate
 from your application code.
 
-_Example: Put React and React DOM into a separate "vendor" chunk:_
+_Example: Put Preact into a separate "vendor" chunk:_
 
 ```js
 module.exports = {
   use: [
-    '@neutrinojs/react',
-    (neutrino) => neutrino.config
-      .entry('vendor')
-        .add('react')
-        .add('react-dom')
+    '@neutrinojs/preact',
+    (neutrino) => {
+      neutrino.config
+        .entry('vendor')
+          .add('preact')
+    }
   ]
 };
 ```
 
 ## Hot Module Replacement
 
-While `@neutrinojs/react` supports Hot Module Replacement your app using React Hot Loader, it does require some
+While `@neutrinojs/preact` supports Hot Module Replacement, it does require some
 application-specific changes in order to operate.
 
-First, install `react-hot-loader` as a dependency, this **must** be React Hot Loader v3+:
-
-#### Yarn
-
-```bash
-❯ yarn add react-hot-loader
-```
-
-#### npm
-
-```bash
-❯ npm install --save react-hot-loader
-```
-
----
-
-- From your `index` entry point (defaults to `src/index.*` from `neutrino.options.entry`), import an `AppContainer`
-from `react-hot-loader`. The main file may be named `index.js` or `index.jsx`. The extension is resolved by Webpack.
-- Wrap your top-level React component in the `AppContainer`.
 - Perform the application render in a reusable function for initial load and subsequent reloads.
 - Add the `hot` acceptance to call this function.
 
 For example:
 
 ```jsx
-import React from 'react';
-import { render } from 'react-dom';
-import { AppContainer } from 'react-hot-loader';
-import MyApp from './MyApp';
-
-const load = () => render((
-  <AppContainer>
-    <MyApp />
-  </AppContainer>
-), document.getElementById('root'));
+import { render } from 'preact';
+import App from './App';
 
+let mount;
+const root = document.getElementById('root');
+const load = (App) => {
+  mount = render(<App />, root, mount);
+};
+ 
 if (module.hot) {
-  module.hot.accept('./MyApp', load);
+  module.hot.accept('./App', () => requestAnimationFrame(() => {
+    load(require('./App').default);
+  ));
 }
+ 
+load(App);
+```
 
-load();
+## Preact Devtools
+
+To use the React Devtools for your Preact project, require the preact devtools during the `development` environment
+within your `entry` file:
+
+```js
+if (process.env.NODE_ENV === 'development') {
+  require('preact/devtools');
+} 
 ```
 
 ## Contributing
@@ -280,8 +287,8 @@ This preset is part of the [neutrino-dev](https://github.com/mozilla-neutrino/ne
 containing all resources for developing Neutrino and its core presets and middleware. Follow the
 [contributing guide](https://neutrino.js.org/contributing) for details.
 
-[npm-image]: https://img.shields.io/npm/v/@neutrinojs/react.svg
-[npm-downloads]: https://img.shields.io/npm/dt/@neutrinojs/react.svg
-[npm-url]: https://npmjs.org/package/@neutrinojs/react
+[npm-image]: https://img.shields.io/npm/v/@neutrinojs/preact.svg
+[npm-downloads]: https://img.shields.io/npm/dt/@neutrinojs/preact.svg
+[npm-url]: https://npmjs.org/package/@neutrinojs/preact
 [spectrum-image]: https://withspectrum.github.io/badge/badge.svg
 [spectrum-url]: https://spectrum.chat/neutrino
diff --git a/packages/react/index.js b/packages/preact/index.js
index 4b03478..832d06f 100644
--- a/packages/react/index.js
+++ b/packages/preact/index.js
@@ -1,6 +1,4 @@
 const web = require('@neutrinojs/web');
-const compileLoader = require('@neutrinojs/compile-loader');
-const loaderMerge = require('@neutrinojs/loader-merge');
 const { join } = require('path');
 const merge = require('deepmerge');
 
@@ -9,58 +7,50 @@ const MODULES = join(__dirname, 'node_modules');
 module.exports = (neutrino, opts = {}) => {
   const options = merge({
     hot: true,
-    babel: {}
-  }, opts);
-
-  Object.assign(options, {
-    babel: compileLoader.merge({
+    babel: {
       plugins: [
         [
           require.resolve('babel-plugin-transform-react-jsx'),
-          { pragma: 'createElement' }
+          { pragma: 'h' }
         ],
         [
           require.resolve('babel-plugin-jsx-pragmatic'),
           {
-            module: 'react',
-            export: 'createElement',
-            import: 'createElement'
+            module: 'preact',
+            export: 'h',
+            import: 'h'
           }
         ],
         require.resolve('babel-plugin-transform-object-rest-spread'),
-        ...(process.env.NODE_ENV !== 'development' ?
-          [[require.resolve('babel-plugin-transform-class-properties'), { spec: true }]] :
-          [])
+        process.env.NODE_ENV !== 'development' ?
+          [require.resolve('babel-plugin-transform-class-properties'), { spec: true }] :
+          {}
       ],
-      presets: [require.resolve('babel-preset-react')],
       env: {
         development: {
           plugins: [
-            ...(options.hot ? [require.resolve('react-hot-loader/babel')] : []),
             [require.resolve('babel-plugin-transform-class-properties'), { spec: true }],
             require.resolve('babel-plugin-transform-es2015-classes')
           ]
         }
       }
-    }, options.babel)
-  });
+    }
+  }, opts);
 
   neutrino.use(web, options);
 
-  neutrino.config.when(neutrino.config.module.rules.has('lint'), () => {
-    neutrino.use(loaderMerge('lint', 'eslint'), {
-      plugins: ['react']
-    });
-  });
-
   neutrino.config
+    .resolveLoader
+      .modules
+        .add(MODULES)
+        .end()
+      .end()
     .resolve
       .modules.add(MODULES).end()
       .extensions.add('.jsx').end()
-      .alias.set('react-native', 'react-native-web').end()
-      .end()
-    .resolveLoader.modules.add(MODULES).end().end()
-    .when(process.env.NODE_ENV === 'development' && options.hot, config => config
-      .entry('index')
-        .prepend(require.resolve('react-hot-loader/patch')));
+      .alias
+        .set('react', 'preact-compat')
+        .set('react-dom', 'preact-compat')
+        .set('create-react-class', 'preact-compat/lib/create-react-class')
+        .set('react-addons-css-transition-group', 'preact-css-transition-group');
 };
diff --git a/packages/react/package.json b/packages/preact/package.json
index 8ff7634..f29657c 100644
--- a/packages/react/package.json
+++ b/packages/preact/package.json
@@ -1,33 +1,28 @@
 {
-  "name": "@neutrinojs/react",
-  "version": "7.3.2",
-  "description": "Neutrino preset for building React web applications",
+  "name": "@neutrinojs/preact",
+  "version": "7.3.1",
+  "description": "Neutrino preset for building Preact web applications",
   "main": "index.js",
   "keywords": [
     "neutrino",
     "neutrino-preset",
-    "react",
+    "preact",
     "web",
-    "hot module replacement"
+    "hot module reload"
   ],
-  "author": "Eli Perelman <eli@eliperelman.com>",
+  "author": "Fahad Hossain <8bit.demoncoder@gmail.com>",
   "license": "MPL-2.0",
-  "repository": "https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/react",
+  "repository": "https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/preact",
   "homepage": "https://neutrino.js.org",
   "bugs": "https://github.com/mozilla-neutrino/neutrino-dev/issues",
   "dependencies": {
-    "@neutrinojs/compile-loader": "^7.3.2",
     "@neutrinojs/loader-merge": "^7.3.2",
     "@neutrinojs/web": "^7.3.2",
     "babel-plugin-jsx-pragmatic": "^1.0.2",
     "babel-plugin-transform-class-properties": "^6.24.1",
     "babel-plugin-transform-es2015-classes": "^6.24.1",
-    "babel-plugin-transform-object-rest-spread": "^6.26.0",
-    "babel-plugin-transform-react-jsx": "^6.24.1",
-    "babel-preset-react": "^6.24.0",
-    "deepmerge": "^2.0.0",
-    "eslint-plugin-react": "^7.5.1",
-    "react-hot-loader": "^3.1.3"
+    "babel-plugin-transform-object-rest-spread": "^6.23.0",
+    "deepmerge": "^2.0.1"
   },
   "peerDependencies": {
     "neutrino": "^7.0.0"
diff --git a/packages/react/test/react_test.js b/packages/preact/test/preact_test.js
similarity index 99%
rename from packages/react/test/react_test.js
rename to packages/preact/test/preact_test.js
index 3733245..698314f 100644
--- a/packages/react/test/react_test.js
+++ b/packages/preact/test/preact_test.js
@@ -12,7 +12,7 @@ test('uses preset', t => {
 
 test('valid preset production', t => {
   const api = Neutrino({ env: { NODE_ENV: 'production' } });
-  
+
   api.use(require('..'));
 
   const errors = validate(api.config.toConfig());

```
