### ISSUE TITLE
Using create-project with yarn doesn't actually use yarn for installation

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#575]
Culprit is:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/create-project/commands/init/utils.js#L94

Due to:

https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/create.js#L18-L32

**Comment by helfi92** [comment]
An alternative would be to go with:

```js
const commandExists = require('command-exists');
const isYarn = commandExists.sync('yarnpkg');
```

**Comment by eliperelman** [comment]
We could, but that doesn't answer whether it was actually used for this command or not. Unfortunately, I haven't found a way to determine that yet, since this is a spawned process and we need information about the parent process.

**Comment by eliperelman** [comment]
I have filed https://github.com/yarnpkg/yarn/issues/5063 on the yarn side.

**Comment by eliperelman** [comment]
As a workaround, we could also just ask the user what the want to use as the last question:

```
Would you like to use npm or yarn for this project?
[ ] npm
[ ] yarn
```

**Comment by helfi92** [comment]
When installing the project, is there a reason why someone would want to use npm rather than yarn if yarn is installed on their machine? If they want to do stuff using `npm`, they could do that after the project is installed.

See how create-react-app handles the situation: https://github.com/facebookincubator/create-react-app/blob/aad5987a0317508562138a8454bb83dd22b8b18f/bootstrap.js#L8-L15

I'm not a big fan of asking another question, but could still work.

**Comment by eliperelman** [comment]
Ok, since we have precedent with CRA, I guess users could come to expect that behavior. I think that solution sounds fine for now.

**Comment by helfi92** [comment]
Sounds good. I'll open a PR today. Are you still ok with https://github.com/mozilla-neutrino/neutrino-dev/issues/575#issuecomment-350325203? Cleaner than the way CRA handles it.
