### ISSUE TITLE
neutrino js role in webpack 4

### ISSUE THREAD

**Issue by CharlesKumar** [mozilla-neutrino/neutrino-dev#721]
webpack 4 is released (on feb 25 2018) and has zero config out of the box

what is the role of neutino js in automating webpack 4 workflow

other than presets (like presets for react )

**Comment by eliperelman** [comment]
Our mission and goals do not change with webpack v4. Just because you can start a super-minimal project with zero config doesn't mean that you get the best experience or the least amount of up-front work. This is where Neutrino steps in. We still provide a great story for distributable and composable configurations.
