### ISSUE TITLE
Setting Environment Variables

### ISSUE THREAD

**Issue by fredguest** [mozilla-neutrino/neutrino-dev#82]
In order to have custom variables available per environment for API keys and such, without committing anything to version control, in https://github.com/facebookincubator/create-react-app for example I can do the following:

1) add the following scripts to `package.json`:

```js
  "start": "sh -ac '. .env.dev; react-scripts start'",
  "stage": "sh -ac '. .env.stg; react-scripts build'",
  "build": "sh -ac '. .env.prd; react-scripts build'",
```

2) add the following files to the root: `.env.dev`, `.env.stg`, `.env.prd`

3) define unique variables per environment to the `.env` files such as:

```js
  REACT_APP_FOO='128376918237691287'
  REACT_APP_BAR='8476547869547955948'
```

4) access those variables anywhere in the source js as follows:

```js
  console.log(process.env.REACT_APP_FOO);
  console.log(process.env.REACT_APP_BAR);
```

How would I accomplish this using Neutrino? I've tried replicating the same process using the `neutrino start` and `neutrino build` scripts but the environment variables end up undefined.

**Comment by pleunv** [comment]
I've done this with DefinePlugin, you can use it as inspiration :)

```js
const globals = {
  __DEV__: process.env.NODE_ENV === 'development',
  __PROD__: process.env.NODE_ENV === 'production',
  __TEST__: process.env.NODE_ENV === 'test'
};

module.exports = ({ config }) => {
  config.plugin('globals')
    .use(webpack.DefinePlugin, globals);
});
```

If you use ESLint you'll also have to add them to the globals there. The snippet below is not entirely correct as they will be defined as _writable_ but I don't know the correct way of doing it due to differences between the eslintrc and ES CLI syntax. One expects an array while the other wants an object, but any attempt at setting _writable_ to `false` has failed. I think @eliperelman might have a bit more knowledge on this subject :)

```js
config.module.rule('lint')
  .loader('eslint', props => merge(props, {
    options: {
      globals: Object.keys(globals)
    }
  }));
```

**Comment by pleunv** [comment]
Rereading your question, I think webpack.EnvironmentPlugin might be better suited to that.

In your case, assuming the environment variables get set during the CI process, you can pass them to your code like this:

```js
config.plugin('env')
  .use(webpack.EnvironmentPlugin, ['REACT_APP_FOO', 'REACT_APP_BAR']);
```

After which you have them available in code as `process.env.REACT_APP_FOO` and `process.env.REACT_APP_BAR`.

However, EnvironmentPlugin is already being used to inject NODE_ENV, so it will have to be merged I think. I'll have to check the proper syntax.

**Comment by fredguest** [comment]
thanks for the help @pleunv! the goal is to have the environment variables read from hidden, uncommitted files files during the execution of the `start` or `build` scripts if possible, but the technique you suggested looks great for different requirements.

**Comment by eliperelman** [comment]
I wrote the [original implementation of environment variables in create-react-app](https://github.com/facebookincubator/create-react-app/pull/342), and am sad to say that I just haven't put this in a preset yet. This doesn't really make sense for a Node.js preset, since it can read from the environment at execution time. For the web preset, maybe it'd be nice if there was a way to specify additional environment variables in package.json.

Extending the environment variables used in `EnvironmentPlugin` right now would not be fun. I think the best workaround solution right now is to extend the plugin to read from those files at build time and inject them.

**Comment by fredguest** [comment]
Ha! That's awesome, I'm a fan of your work on create-react-app :). Ok cool, the only problem with defining variables in `package.json` would be that they'd be committed to version control obviously, but the `EnvironmentPlugin` solution is workable.

**Comment by trusktr** [comment]
My Ops team needs to assign those at runtime. How can we do that? I'm using `neutrino-preset-node` to run a server. It'd be great for the server to receive those env vars at runtime, dynamically, while still using process.env.WHATEVER, not transpiled-in at build time.

**Comment by u0078867** [comment]
You can add `@neutrinojs/env`:

```js
module.exports = {
  use: [
    ...
    ['@neutrinojs/env', ['MY_VAR']], // 1
    //['@neutrinojs/env'],  // 2 - does not work
  ]
};
```
For case 1, however, if `MY_VAR` is not set, you will get a warning from `webpack.EnvironmentPlugin` that there is no default value;

**Comment by edmorley** [comment]
Hi! The ability to set default values has been added to the web preset in #983, which will be in the upcoming Neutrino 9.

In the meantime (or for presets that don't inherit from web, that don't have the built-in `env` preset option), you can use the Neutrino API to add `EnvironmentPlugin`:

```js
 const { EnvironmentPlugin } = require('webpack');

module.exports = {
  use: [
    ['<existing preset name>', {
      // Options
    }],
    (neutrino) => {
      neutrino.config
        .plugin('env')
        .use(EnvironmentPlugin, [{
          MY_VAR: 'default-value',
        }]);
    }
  ]
};
```

**Comment by u0078867** [comment]
Oh lovely, this is precious!

**Comment by WhoAteDaCake** [comment]
I am using
```
const { EnvironmentPlugin } = require("webpack");
module.exports = {
  use: [
    [
      "@neutrinojs/react-components",
      {
        devServer: {
          // Disabling options.hot will also disable devServer.hot
          hot: true,
          // Proxy requests that don't match a known file to the specified backend.
          proxy: "https://127.0.0.1:9000/v1"
        }
      }
    ],
    neutrino => {
      neutrino.config
        .plugin("env")
        .use(EnvironmentPlugin, [{ TEST: JSON.stringify("test") }]);
      // .use(EnvironmentPlugin, ["URL", "TOKEN", "PROJECT"]);
    }
  ]
};
```
However it does not inject variables to `process.env` on the frontend

**Comment by edmorley** [comment]
Hi! Testing your snippet works for me locally using Neutrino 8.3.0?

Though note the [EnvironmentPlugin docs](https://webpack.js.org/plugins/environment-plugin/) say:

> Unlike DefinePlugin, default values are applied to JSON.stringify by the EnvironmentPlugin. 

...so the `JSON.stringify()` is unnecessary (and adds extra quotes). Without knowing how you're testing this, it's hard to know if that fixes your issue (eg if you were checking for the exact value, as opposed to whether it was set at all)?

Failing that, I would:
* check that you're using a webpack version that includes [this upstream fix](https://github.com/webpack/webpack/commit/8da8b93ed433c9491b28243b62d260deed98c4d8) (webpack 3.11+), which should be the case since Neutrino 8.3.0 sets the webpack dependency as `^3.12.0`.
* look at the output from `--inspect` for further clues:
https://neutrinojs.org/cli/#-inspect
