### ISSUE TITLE
Correlation or cooperation with Parcel?!

### ISSUE THREAD

**Issue by tbsvttr** [mozilla-neutrino/neutrino-dev#864]
It is not really a problem, but only a thought I have. This project seems very similar in scope to [Parcel](https://parceljs.org/). Maybe it would be interesting for the maintainers to have a loot at it. Maybe codesharing or cooperation could be a possibility.

**Comment by edmorley** [comment]
Hi! Thank you for reaching out :-)

The Neutrino project is in the same ballpark as [create-react-app](https://github.com/facebook/create-react-app), [nwb](https://github.com/insin/nwb) and [similar](https://reactjs.org/community/starter-kits.html) - in that it's a wrapper around webpack/babel/eslint/... designed to reduce the amount of boilerplate/frustration/research required when setting up the development/testing/build workflow for a modern frontend project (compared to using webpack/... directly).

Parcel on the other hand is a web application bundler (ie an alternative to webpack, rather than a wrapper around it) which does look very interesting - and it's possible they have a few tricks that webpack could take inspiration from. For more details on their design approach compared to other bundlers, see:
https://github.com/parcel-bundler/parcel#why-parcel

**Comment by eliperelman** [comment]
Closing as answered.
