### ISSUE TITLE
Try to be more explicit in what's (not) supported in presets/middleware

### ISSUE THREAD

**Issue by avaragado** [mozilla-neutrino/neutrino-dev#883]
Issue created as a result of a [Spectrum thread](https://spectrum.chat/?t=6beb2d28-5027-4d69-a886-df4f489fe32c).

As someone trying out neutrino for the first time, I quickly hit a problem: it seems that the library preset doesn't support `babel-plugin-transform-object-rest-spread`.

The doc page for the library preset, https://neutrino.js.org/packages/library/, is vague about what's actually supported and not supported by the library. It says:

> Modern Babel compilation supporting ES modules, async functions, and dynamic imports

OK, it doesn't explicitly mention object rest/spread. But that's a feature certainly covered by "modern", and helpers like `create-react-app` support it.

The point is, I had to guess.

Presets should ideally be explicit about the features they support. Stating what is NOT supported is also extremely helpful in many cases.

**Comment by AlanFoster** [comment]
I've ran in to the exact same problem as yourself @avaragado 

Tests passed, linting passed, but compilation failed. I've now updated my `.neutrinorc.js` file to configure babel:

```javascript
const loaderMerge = require("@neutrinojs/loader-merge");

module.exports = {
  use: [
    // ...,

    (neutrino) => {
      neutrino.use(loaderMerge('compile', 'babel'), {
        plugins: ['transform-object-rest-spread']
      });
    }
  ]
};
```

I've sent a PR to correct the example usage of `loaderMerge` now too https://github.com/mozilla-neutrino/neutrino-dev/pull/890

**Comment by edmorley** [comment]
Hi! I agree the docs could be clearer here - there's no point having useful new ES6 features available and not people not realising - and conversely, it's frustrating if something you expect to work doesn't.

Looking at the `release/v8` branch, I see that for some reason `babel-plugin-transform-object-rest-spread` is only enabled when using the `@neutrinojs/react` or `@neutrinojs/preact` presets:
https://github.com/mozilla-neutrino/neutrino-dev/blob/v8.2.3/packages/react/index.js#L31
https://github.com/mozilla-neutrino/neutrino-dev/blob/v8.2.3/packages/preact/index.js#L24

...but not for eg `@neutrinojs/web` or `@neutrinojs/library`:
https://github.com/mozilla-neutrino/neutrino-dev/blob/v8.2.3/packages/web/index.js#L89-L102
https://github.com/mozilla-neutrino/neutrino-dev/blob/v8.2.3/packages/library/index.js#L32-L48

The docs for the web/library preset don't menton rest/spread (matching the truth at least), and the react/preact ones say:
> * Modern Babel compilation adding JSX, object rest spread syntax, and class properties.

@eliperelman, it seems like `transform-object-rest-spread` should be enabled consistently across the board for Neutrino 8 - would you be fine with that being changed (/calling it non-breaking)?

For what it's worth this is fixed on neutrino `master` thanks to the update to babel 7 (since the newer preset-env supports it natively, so no need to manually add a plugin):
https://github.com/babel/babel/blob/v7.0.0-beta.47/packages/babel-preset-env/data/plugins.json#L227-L235

**Comment by edmorley** [comment]
v8.3.0 has just been released, that adds object-rest-spread support to the web and library presets (#940). And #890 (and the `release/v8` equivalent) fixed the loader-merge examples.

Are there any other changes to the documentation needed for this issue, or can this now be closed? :-)

**Comment by avaragado** [comment]
I think it can be closed.
