### ISSUE TITLE
Properly set `mode` and `NODE_ENV` for test middleware

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#900]
In the v8 line of Neutrino we manually default `NODE_ENV` to `test` when running the test command. With the removal of the Neutrino CLI, we would no longer have a test command, but we do still have testing middleware via the karma, mocha, and jest presets. We should ensure that we have a reasonable value for the `config.mode` and `NODE_ENV` for test middleware to rely on while trying to get the least number of config permutations.

At the outset, I'm wondering if we should have `--mode none` and `NODE_ENV=test`, but I think @edmorley had concerns about this particular mode. Also need to ensure that these values can be easily overridden from the host environment.

**Comment by edmorley** [comment]
I've been experimenting with setting mode to `development` when using Karma.

I've finally got it working, however I can see from the webpack build console output that the hot reloader configs are being added. This doesn't break anything, but is another side-effect of consolidating 9+ different permutations of configuration (`command = {start, build, test, ...}` x `NODE_ENV = {production, development, test}`) into just two (`mode = {development, production}`).

I'd be open to considering `mode=none` as a way to add a third state, though it would disable some of the webpack development features that might be useful for testing (eg named modules), so we'd want to vet those:
https://github.com/webpack/webpack/blob/v4.10.2/lib/WebpackOptionsDefaulter.js#L257-L266

Other possible options:

1) Make Neutrino support a `mode` of 'test', that gets translated to 'development' in the webpack config, but sets NODE_ENV to 'test'. Presets would then be encouraged to check the value of NODE_ENV rather than `mode`, so they would see all three states, not just the 2 stats of `mode`. (Though having Neutrino's `mode` support extra options is kinda confusing, so not sure this is ideal.)

2) Encourage presets to use NODE_ENV to check for development/production/test, and allow the adapters (`neutrino().karma()` etc) to set both a default mode and NODE_ENV.

**Comment by edmorley** [comment]
This is a blocker for releasing a v9 alpha. @eliperelman do you know when you might be able to take a look at this?

**Comment by eliperelman** [comment]
I'll try and start on this today.
