### ISSUE TITLE
Easier mechanism to add babel-polyfill

### ISSUE THREAD

**Issue by jaridmargolin** [mozilla-neutrino/neutrino-dev#93]
So please bare with me as I am new to neutrino and embarrassingly babel as well (actually one of the reasons I decided to proceed with neutrino).

I introduced a few features into my application that required babel-polyfill. Unfortunately adding it to my project was not as elegant as I would hope. I ended up with:

```
module.exports = ({ config }) => {
  const CWD = process.cwd()
  const SRC = path.join(CWD, 'src')
  const APP_ENTRY_PATH = path.join(SRC, 'index.js')

  config.entry('index')
     .delete(APP_ENTRY_PATH)
     .add('babel-polyfill')
     .add(APP_ENTRY_PATH)
}
```

This dance is required because I need to have babel-polyfill defined as an entry prior to my app entry file.

It would be great if there was either a mechanism to specify index (which may not be possible as the current data structure utilizes a Set), or a simpler api/toggle to add babel-polyfill.

My thoughts aren't completely wrapped around how this should behave, I just found it to be a clumsy experience (either due to the api, or due to my ignorance 😂).

**Comment by eliperelman** [comment]
It's funny you brought this up, because at the moment I am adding babel-polyfill by default to the index entry. This will probably land in v5, but still wanted to address your question.

In addition to the approach you took to adding babel-polyfill, you can also import it directly from your entrypoint:

```js
import 'babel-polyfill';
import React from 'react';
// ...
```

You can also add it from your package.json:

```json
{
  "config": {
    "neutrino": {
      "entry": {
        "index": ["babel-polyfill"]
      }
    }
  }
}
```

**Comment by eliperelman** [comment]
Looking over your preset override, you can also use `prepend` for polyfill and avoid the deletions and re-additions:

```js
module.exports = ({ config }) => {
  config.entry('index').prepend('babel-polyfill');
}
```

**Comment by jaridmargolin** [comment]
Prepend solution looks great. 

Out of curiosity, is this method documented? I do not see it in the [documentation for webpack-chain](https://github.com/mozilla-rpweb/webpack-chain/blob/master/README.md). I do however see it in the [src](https://github.com/mozilla-rpweb/webpack-chain/blob/5f0b0c670e6ad946e0232a208abb667f749aeba4/src/ChainedSet.js#L14).

**Comment by eliperelman** [comment]
Oo, good find, looks like it's not documented. I'll fix that up.

**Comment by jaridmargolin** [comment]
Awesome. Thank you for the help and prompt replies!

**Comment by eliperelman** [comment]
My pleasure!

**Comment by monkindey** [comment]
hi, @eliperelman , thanks for your funny neutrino project. I am new to neutrino, 😂 I want to remove the babel-polyfill for the lastest chrome so that easy to debug the generator. But I saw [that](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L77), the generator transform will be default? Any thought about that?

**Comment by gormonn** [comment]
What is best way to add `babel-polyfill` in Neutrino v8 ?

**Comment by avdeev** [comment]
This solution add 2 more files in `build` for the react-components preset
