### ISSUE TITLE
What if I dont like webpack-chain, does that prevent me from using neutrino?

### ISSUE THREAD

**Issue by hulkish** [mozilla-neutrino/neutrino-dev#97]

**Comment by eliperelman** [comment]
It doesn't prevent you from using Neutrino, nor does it prevent you from doing basic overrides from package.json. If you want to do advanced configuration, then yes, you would have to use webpack-chain since it is our mechanism for maintaining stateful configurations across presets and middleware, which you **cannot** do with standard webpack configuration.

**Comment by hulkish** [comment]
my drawback with `webpack-chain` at this time is mainly due to the work that would be involved with covering the gaps that they currently haven't gotten to yet. Not knocking it at all... just to clarify.

**Comment by eliperelman** [comment]
@hulkish I completely understand, and have been working to resolve that. I should be publishing v2.0.0 of webpack-chain tomorrow which should give the API full coverage of shorthand methods. To be clear, webpack-chain currently allows you to configure all of Webpack, it's just that you have to use some of the lower-level methods to do it.

**Comment by eliperelman** [comment]
Keeping open so we can add this question to the FAQs.

**Comment by eliperelman** [comment]
Updated docs to address.
